hadoop_streaming_jar: /usr/lib/hadoop-mapreduce/hadoop-streaming.jar
mapper_path: /home/hadoop/mapper.py
reducer_path: /home/hadoop/reducer.py
input_output_dir: /user/hadoop
element_path: /home/hadoop/elements.json
local_in_out_dir: /home/hadoop
emr_dns: "emr/dns_name"
key_file: "path/to/emr-key-pair.pem"
username: "ec2-user"
local_mapper: ./MapReduce/mapper.py
local_reducer: ./MapReduce/reducer.py
data_file: ./NetflixShows.csv
local_element: ./config/elements.json
